name: provider_clean_architecture
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  pretty_dio_logger: ^1.1.1
  fluttertoast: ^8.0.8
  shared_preferences: ^2.0.10
  jiffy: ^6.2.1
  uuid: ^3.0.6
  dio: ^5.0.3
  provider: ^6.1.2
  logger: ^2.4.0
  firebase_crashlytics: ^3.3.6
  firebase_core: ^2.16.0
  faker: ^2.1.0
  dartz: ^0.10.1
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

